version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarcloud: sonarsource/sonarcloud@2.0.0
  ggshield: gitguardian/ggshield@1.1.4

jobs:
  build:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg-agent \
                software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo /etc/init.d/docker start
      - run:
          name: Check Docker version
          command: docker --version && docker info
      - run:
          name: Build Docker image
          command: |
            cd docker-sergi-main
            docker build -t ci/cd_app_sergi:latest .
      - run:
          name: Install Dependencies
          command: |
            pip install coverage pylint pytest ggshield
      - run:
          name: Install Curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip default-jre sudo git
      - run:
          name: Copy files to /app and list contents
          command: |
            mkdir logs
            touch app.json
            cp -r . /app
      - run:
          name: Run Tests
          command: |
            pytest /app/tests
      - run:
          name: Informe de cobertura
          command: |
            coverage run -m pytest tests
            coverage report -m
          working_directory: /app
      - run:
          name: Run Linting with pylint
          command: pylint app
          working_directory: /app
      - run:
          name: GitGuardian Auth
          command: |
            curl -H "Authorization: Token ${GITGUARDIAN_API_KEY}" \
            https://api.gitguardian.com/v1/health
      - run:
          name: GitGuardian Scan
          command:
            ggshield secret scan commit-range HEAD
      - store_artifacts:
          path: /app/artifacts
          destination: artifacts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
