version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: sergicasti/practicak8ssergi:latest
    steps:
      - checkout      
      - run:
          name: Install Dependencies
          command: |
            pip install coverage pylint pytest
      - run:
          name: Prueba Temp ls
          command: |
            ls
      - run:
          name: Run Tests
          command: pytest /app/tests
          working_directory: /app
      - run:
          name: Generate Coverage Report
          command: coverage report -m
          working_directory: /app
      - run:
          name: Run Linting with pylint
          command: pylint app
          working_directory: /app
      - sonarcloud/scan:
          cache_version: 1
          project_root: /app
          sonar_token_variable_name: "SecToken"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
