version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarcloud: sonarsource/sonarcloud@2.0.0
  ggshield: gitguardian/ggshield@1.1.4

jobs:
  build:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout            
      - run:
          name: Install Dependencies
          command: |
            pip install coverage pylint pytest ggshield psycopg2 flask json-log-formatter
      - run:
          name: Install Curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip default-jre sudo git
      - run:
          name: Copy files to /app and list contents
          command: |
            ls
      - run:
          name: Run Tests
          command: |
            pytest tests
      - run:
          name: Informe de cobertura
          command: |
            coverage run -m pytest tests
            coverage report -m
      - run:
          name: Run Linting with pylint
          command: |
            touch app/__init__.py
            pylint app
      - run:
          name: GitGuardian Auth
          command: |
            curl -H "Authorization: Token ${GITGUARDIAN_API_KEY}" \
            https://api.gitguardian.com/v1/health
      - run:
          name: GitGuardian Scan
          command:
            ggshield secret scan commit-range HEAD
      # Generar paquete PyPI
      - run:
          name: Build PyPI Package
          command: |
            python setup.py sdist
      
      # Listar los contenidos de 'dist'
      - run:
          name: List Contents of Dist
          command: |
            echo "Contenido de 'dist':"
            ls dist

      # Guardar el paquete generado como artefacto
      - store_artifacts:
          path: dist
          destination: pypi_package

      # Persistir el directorio 'dist' al espacio de trabajo
      - persist_to_workspace:
          root: .
          paths:
            - dist


  deploy:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      # Adjuntar el espacio de trabajo para acceder al directorio 'dist'
      - attach_workspace:
          at: .

      # Instalar twine para subir el paquete a PyPI
      - run:
          name: Install Twine
          command: |
            pip install twine

      - run:
          name: Subir paquete a PyPI
          command: |
            twine upload --repository-url https://upload.pypi.org/legacy/ --username __token__ --password "$pypi_key" dist/*


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
