version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarqube: drift/sonarqube@2.0.6

jobs:
  build:
    docker:
      - image: sergicasti/practicak8ssergi:latest
    steps:
      - checkout
      - run:
          name: Dependencias
          command: |
            pip install coverage pylint pytest
          working_directory: /app
      #- run:
      #    name: Run tests
      #    command: pytest
      - run:
          name: Generate coverage report
          command: coverage report -m
      - run:
          name: Ejecutar linting con pylint
          command: pylint app
      - sonarqube/analyze
      - run:
          name: Generate artifact
          command: python setup.py sdist
      - run:
          name: Publish artifact
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              twine upload dist/*
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
