version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarcloud: sonarsource/sonarcloud@2.0.0
  ggshield: gitguardian/ggshield@1.1.4

jobs:
  build:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout            
      - run:
          name: Install Dependencies
          command: |
            pip install coverage pylint pytest ggshield psycopg2 flask json-log-formatter
      - run:
          name: Install Curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip default-jre sudo git
      - run:
          name: Copy files to /app and list contents
          command: |
            ls
      - run:
          name: Run Tests
          command: |
            pytest tests
      - run:
          name: Informe de cobertura
          command: |
            coverage run -m pytest tests
            coverage report -m
      - run:
          name: Run Linting with pylint
          command: pylint app
      - run:
          name: GitGuardian Auth
          command: |
            curl -H "Authorization: Token ${GITGUARDIAN_API_KEY}" \
            https://api.gitguardian.com/v1/health
      - run:
          name: GitGuardian Scan
          command:
            ggshield secret scan commit-range HEAD
      - store_artifacts:
          path: /app/artifacts
          destination: artifacts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
