version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarcloud: sonarsource/sonarcloud@2.0.0
  gitguardian: gitguardian/gg-action@1.0.0

jobs:
  build:
    docker:
      - image: sergicasti/practicak8ssergi:latest
    environment:
      GITHUB_TOKEN: 9d30a49ed7F8DdBEd610fb3E0e6dd8becf9CAD1607D86fbE22de8ea1ecf6d8A167B23Fd
    steps:
      - checkout      
      - run:
          name: Install Dependencies
          command: |
            pip install coverage pylint pytest
      - run:
          name: Install Curl
          command: |
            apt-get update
            apt-get install -y curl unzip default-jre sudo
      - run:
          name: Copy files to /app and list contents
          command: |
            ls
            mkdir logs
            touch app.json
            cp -r . /app
            ls /app            
      - run:
          name: Run Tests
          command: |
            pytest /app/tests          
      - run:
          name: Informe de cobertura
          command: |
            coverage run -m pytest tests
            coverage report -m
          working_directory: /app
      - run:
          name: Run Linting with pylint
          command: pylint app
          working_directory: /app
      - sonarcloud/scan:
          cache_version: 1
          project_root: /app
          sonar_token_variable_name: "SONAR_TOKEN"
      - gitguardian/scan:
